name: Continuous Integration
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install Javascript dependencies
      run: npm install

    - name: Build
      run: npm run build
