name: Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
        
      - name: Deploy to Hetzner Cloud using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/youtube.com/
            git pull origin main
            npm install
